/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package au.com.seek.traffic;
import au.com.seek.traffic.parser.Parser;
import au.com.seek.traffic.parser.impl.FileParser;
import au.com.seek.traffic.exception.ParseException;
import java.io.File;
public class App {

    public static void main(String[] args) {
        try {
            new FileParser(new File("n.txt")).parse();
        } catch(ParseException e) {
            System.out.println("caught wth error"+e.getMessage());
        }
    }
}
